resources/docker-compose-regtest-liquid.yml
resources/volumes/liquidregtest/liquid-config/liquid.conf

This closes #34 and closes #31

Liquid faucet fixes

---

README.md
cli/cmd/flags.go
cli/cmd/start.go
cli/cmd/stop.go
cli/main.go
scripts/clean

* Pretty start logs
* move `.env` to `~/.nigiri` instead of being floating into fllesystem
* add `scripts/clean` for development. Closes #37 
* add `--version` flag. Closes #36 
NOTE: paths must be changed before merging

Enhancements

---

cli/cmd/flags.go
cli/cmd/logs.go
cli/cmd/logs_test.go
cli/cmd/start.go
cli/cmd/start_stop_test.go
cli/cmd/stop.go
cli/config/main.go
cli/constants/constants.go
cli/controller/controller.go
cli/controller/docker.go
cli/controller/env.go
cli/controller/parser.go
cli/controller/parser_test.go
resources/docker-compose-regtest-liquid.yml
resources/docker-compose-regtest.yml

This fixes #32.
This should be merged after [this one](https://github.com/vulpemventures/docker-esplora/pull/1), when a new esplora docker image has been released.

Changes for new version of esplora image

---

cli/cmd/flags.go

Bump version

---

resources/docker-compose-regtest-liquid.yml
resources/volumes/liquidregtest/liquid-config/elements.conf

Use --parent-network=regtest in Electrs-Liquid; txindex=1 in Elements.conf

---

README.md
resources/docker-compose-regtest-liquid.yml
resources/docker-compose-regtest.yml

- Added container_names: it closes #71 
- Removed deprecated links directive: it closes #72
- Added Nigiri Travis reference in documentation: it closes #74 
- Updated container_name related documentation
- Added necessary dependencies

container_names and links directive

---

cli/cmd/flags.go
cli/cmd/rpc.go
cli/cmd/rpc_test.go
cli/cmd/start_stop_test.go

Added rpc command

---

cli/cmd/flags.go
cli/cmd/mint.go
cli/cmd/mint_test.go
cli/cmd/start_stop_test.go

Added mint command

---

cli/cmd/flags.go
cli/cmd/push.go
cli/cmd/push_test.go
cli/cmd/start_stop_test.go

Added Push Command. This fixes #92

Added push command

---

README.md

Added suggestion about adding docker to sudoers

---

cli/cmd/push_test.go
cli/cmd/version.go
cli/constants/constants.go
cli/controller/docker.go
resources/docker-compose-regtest-liquid.yml
resources/docker-compose-regtest.yml
resources/volumes/liquidregtest/config/bitcoin.conf
resources/volumes/liquidregtest/liquid-config/elements.conf
resources/volumes/regtest/config/bitcoin.conf

* Use new images from GH container registry
* Split `NigiriImages` to allow to have more robust check if nigiri is running or not
* add fallbackfee to bitcoin.conf & elements.conf
BONUS:
* remove check if nigiri is runnig for the `version command`. Not needed

Use GH container registry images

---

cmd/nigiri/resources/docker-compose.yml
go.sum

add `user: 1000:1000` in liquid container (docker-compose.yml)

---

README.md

Added instructions on where to find the config files

---

cmd/nigiri/cln.go
cmd/nigiri/lnd.go
cmd/nigiri/start.go

This fixes https://github.com/vulpemventures/nigiri/issues/147﻿
This fixes https://github.com/vulpemventures/nigiri/issues/149

Run also LN services in headless mode

---

README.md

Add an example sending Liquid asset

---

cmd/nigiri/rpc.go
go.mod
go.sum

Before 
```
{
"chain": "regtest",
"blocks": 101,
"headers": 101,
"bestblockhash": "7bd67b54683ab475133906e776b5c927b23c77a5cf7d7fa1df464908060f45f9",
"difficulty": 4.656542373906925e-10,
"time": 1670099509,
"mediantime": 1670099508,
"verificationprogress": 1,
"initialblockdownload": false,
"chainwork": "00000000000000000000000000000000000000000000000000000000000000cc",
"size_on_disk": 30476,
"pruned": false,
"warnings": ""
}
```
now 
```json
{
"bestblockhash":  "7bd67b54683ab475133906e776b5c927b23c77a5cf7d7fa1df464908060f45f9",
"blocks":  101,
"chain":  "regtest",
"chainwork":  "00000000000000000000000000000000000000000000000000000000000000cc",
"difficulty":  4.656542373906925e-10,
"headers":  101,
"initialblockdownload":  false,
"mediantime":  1670099508,
"pruned":  false, …
```

colorize json output

---

cmd/nigiri/resources/docker-compose.yml

Improve cln docker service definition

---

README.md

improve readme by showing how to pay invoices between cln and lnd
@altafan please review

readme: how to pay invoices between cln and lnd

---

README.md
cmd/nigiri/main.go

chore: fix some typos in comment

---

cmd/nigiri/resources/docker-compose.yml

update bitcoin image to v29
closes https://github.com/vulpemventures/nigiri/pull/220
@tiero @Kukks @altafan please review

use ghcr.io/getumbrel/docker-bitcoind:v29.0

---

cmd/nigiri/resources/docker-compose.yml

Updates ark image to latest `ghcr.io/arkade-os/ark:v0.6.2`
Please @tiero review

Update ark image

---

cmd/nigiri/faucet.go
cmd/nigiri/resources/docker-compose.yml
cmd/nigiri/start.go

```bash
nigiri start --ark --setup-ark
```
* starts arkd 
* starts ark-wallet
* setup and faucet ark-wallet with 10 BTC
* setup and faucet ark-cli "offchain" wallet with 1 vBTC
@Kukks @tiero @altafan please review

update to arkd v0.7.0 + arkd setup on startup
